---
- name: Create data dir
  become: yes
  file:
    path:
      - /data/mongo
    recurse: yes

- name: Start MongoDB container
  become: yes
  command: |
    docker run -d --name container-mongo -p 27017:27017
    -d --restart always
    -e MONGO_INITDB_ROOT_USERNAME=mongoadmin
    -e MONGO_INITDB_ROOT_PASSWORD=secret
    -v /data/mongo:/data/db
    mongo
  ignore_errors: yes
