defaults:
  image: ghcr.io/naft-a/keypea/secrets-service
  imageTag: latest
  network:
    mode: host
  env:
    RACK_ENV: "production"
    API_TOKEN: "31AExh4Ai0tEXnfeL6mGAa7Gt"
    MONGODB_HOST: "127.0.0.1"
    MONGODB_USER: "mongoadmin"
    MONGODB_PASSWORD: "secret"

processes:
  web:
    command: ["bundle", "exec", "puma", "-C", "config/puma.rb"]
    caddy:
      hostnames:
        - secretsservice.keypea.app
    readyCheck:
      frequency: 2s
      maximum: 60
      http:
        expectedStatus: 200
        path: /
        headers:
          - name: Host
            value: secretsservice.keypea.app

tasks:
  create_indexes:
    command: ["rake", "db:mongoid:create_indexes"]

  console:
    command: ["bundle", "exec", "rack-console"]
    interactive: true
